### PR TITLE
[Storage] Truncate long command str in `sky storage ls`

### PR DESCRIPTION
**Pull request by romilbhardwaj**
Truncates long `COMMAND` strs in `sky storage ls`, like we do in `sky status`.

Before:
```
(base) ➜  ~ sky storage ls
NAME                       CREATED     STORE  COMMAND                                   STATUS
romil-debug-parq           22 hrs ago  S3     sky launch parquet_test.yaml --cloud gcp  READY
```

After:
```
(base) ➜  ~ sky storage ls
NAME                       CREATED     STORE  COMMAND                       STATUS
romil-debug-parq           22 hrs ago  S3     sky launch parquet_test.y...  READY

...

(base) ➜  ~ sky storage ls -a    
NAME                 CREATED    STORE  COMMAND                                                                                                                            STATUS  
sky-test-1688589264  1 day ago  S3     sky launch -y -c t-kubernetes-sto363-2ea4-d7 --cloud kubernetes /var/folders/98/hhq8wrtx6y13196q61xphjsm0000gn/T/tmp4ev9pbqq.yaml  INIT    
sky-test-1688589292  1 day ago  S3     sky launch -y -c t-kubernetes-sto363-2ea4-54 --cloud kubernetes /var/folders/98/hhq8wrtx6y13196q61xphjsm0000gn/T/tmpwbfcbv4x.yaml  READY  
```

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [x] `pytest tests/test_smoke.py::TestStorageWithCredentials`

### CODE REVIEW

**Review by landscapepainter — COMMENTED** [review]
I'm wondering if we should add `-a` option for `sky storage ls` as well if we are going to truncate `COMMAND` as a default. `-a`, `--all` would allow the user to see the full `COMMAND`. `sky launch` command with task yaml and some options used will always get truncated.

**Comment by romilbhardwaj** [comment]
@landscapepainter good idea - added `-a` flag to print without truncation.

**Review by landscapepainter — COMMENTED** [review]
Thanks for adding the support for `--all` @romilbhardwaj ! I tested out the flag and this should be ready to go after adding the support in the doc, `docs/source/reference/cli.rst`, for the newly added flag.

**Review by landscapepainter — APPROVED** [review]
lgtm! @romilbhardwaj

**Pull request merged**
