### PR TITLE
Add a pre commit config to help format before pushing

### PR DESCRIPTION
**Pull request by zpoint**
Step 1 install pre-commit

```bash
pip install pre-commit
# in the project root of skypilot repo
pre-commit install
# Make sure the .pre-commit-config.yaml file is in your project root, as demonstrated in this PR.
```

Step 2, now just run `git commit`. The command will use the `pre-commit` hook, it will behave exactly the same as [format.sh](https://github.com/skypilot-org/skypilot/blob/master/format.sh)

image

Refer to this [comment](https://github.com/skypilot-org/skypilot/pull/4258#issuecomment-2469513779) if you're using cursor/vscode and encounter env problem

Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `conda deactivate; bash -i tests/backward_compatibility_tests.sh`

### CODE REVIEW

**Comment by Michaelvll** [comment]
Thanks @zpoint! I was testing it in one of my PR #4264 and trying to use the commit in vscode/cursor's GUI, but it seems the pre-commit hook was not triggered. Do you know how to get it work?
image

**Comment by zpoint** [comment]
@Michaelvll 

I guess it's because you installed the pre-commit in terminal using Python environment A. If you use the terminal to commit, then it should trigger. 

However, Cursor/VSCode is launched by Python environment B, and if you use Cursor to commit, it doesn't have pre-commit installed. 

I will try to find a way to make it work in Cursor/VSCode.

**Comment by zpoint** [comment]
Could you take a look when you have time? Thanks @Michaelvll

**Comment by Michaelvll** [comment]
```
Fixing sky/jobs/controller.py

fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
black................................................(no files to check)Skipped
isort....................................................................Passed
isort................................................(no files to check)Skipped
yapf.....................................................................Failed
- hook id: yapf
- files were modified by this hook
pylint...................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

Executable `mypy` not found
```
Thanks @zpoint! Just realized that I did not install pre-commit in my python env. After installing it, it shows the above error for failing to find `mypy` in VSCode/Cursor's git integration, although I do have mypy installed in my separate python env for skypilot. Is there away for the VSCode git integration to correctly pick up the env?

**Comment by zpoint** [comment]
@Michaelvll 

VSCode seems not to provide a way to configure the environment when you click the `commit` on the GUI menu.
This [issue](https://github.com/microsoft/vscode-python/issues/10165) is still opened for VSCode after 4 years.

## Workaround1: 
The workaround is to start VSCode from the command line after you activate your environment; in this way, VSCode will carry all the environment variables from your command line.

If you are not using `zsh`, refer to: [how-to-open-cursor-from-terminal](https://forum.cursor.com/t/how-to-open-cursor-from-terminal/3757/6)

```
# add this to the tail of your ~/.zshrc
function cursor {
  open -a "/Applications/Cursor.app" "$@"
}

# activate my env
conda activate sky
# now, cursor will start with current env
cursor .
``

## workaround2

Install `mypy` globally in the global Python environment, which is not elegant.

**Review by Michaelvll — APPROVED** [review]
Thanks @zpoint! I am good with having this PR in. Could we add a TODO comment in the config yaml to keep it sync with the format.sh. We should add the instruction in the developer docs and mark it optional: https://docs2.skypilot.co/en/latest/developers/CONTRIBUTING.html

**Comment by zpoint** [comment]
Updated the document. Could you help take another look before merging? @Michaelvll

**Comment by zpoint** [comment]
I double-checked and fixed this configuration; it should now match the `format.sh` script.  @Michaelvll

**Comment by zpoint** [comment]
[Cusor](https://github.com/skypilot-org/skypilot/pull/4258#issuecomment-2458072739)

This won't be a problem now. I have configured the pre-commit file to use its own environment instead of the local one. As long as the pre-commit command is in your `PATH` and Cursor can find it, everything will work fine.

**Pull request merged**
