### PR TITLE
[Storage] Replacing aws s3 sync with s5cmd with much faster speed

### LINKED ISSUE #2176: [Feature Request] s5cmd command support for COPY Persistent Data Storage
Persistent Data Storage that is COPYéd can be quite slow to copy.

[s5cmd](https://github.com/peak/s5cmd) is MUCH faster at uploading and downloading from S3 / R2 that s3cmd and aws-cli. Like MUCH faster: "For uploads, s5cmd is 32x faster than s3cmd and 12x faster than aws-cli. For downloads, s5cmd can saturate a 40Gbps link (~4.3 GB/s), whereas s3cmd and aws-cli can only reach 85 MB/s and 375 MB/s respectively."

NOTE: s5cmd is only fast when it can parallelize into many downloads. It is of comparable speed if you are just downloading one big file.

### PR DESCRIPTION
**Pull request by landscapepainter**
This PR closes #2176 

User requested to use `s5cmd sync` instead of `aws s3 sync` for our storage upload and downloads due to it's speed. [Confirmed it has most of necessary functionalities with a much faster speed](https://github.com/skypilot-org/skypilot/issues/2176#issuecomment-1636993365). As `s5cmd` does not have `--include` option implemented [yet](https://github.com/peak/s5cmd/issues/516), I will leave `storage.py/S3Store.get_file_sync_command` as it is. 

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [x] `sky launch s3_storage.yaml` 
`s3_storage.yaml`:
```
file_mounts:
  /s3-file: s3://s3-doyoung-test-file/test-file.yaml

  /s3-copy-dir: 
    name: s3-doyoung-copy-testing
    source: ~/s3-cos-copy
    store: s3
    mode: COPY

  /s3-copy-file:
    name: s3-doyoung-copy-file-testing
    source: [~/test-file.yaml]
    store: s3
    mode: COPY
```
- [x] Relevant individual smoke tests: `pytest tests/test_smoke.py::TestStorageWithCredentials`
- [x] pytest tests/test_smoke.py::test_aws_storage_mounts --aws

### CODE REVIEW

**Comment by romilbhardwaj** [comment]
Thanks @landscapepainter. Just noting our offline discussion here - instead of _replacing_ `aws cli`, we want to first use `s5cmd` if it is installed, and if not installed we want to fall back to `aws cli`.

**Comment by concretevitamin** [comment]
Hey @landscapepainter - could we quickly check if the `crt` client is faster than s5cmd? https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#preferred-transfer-client

**Comment by landscapepainter** [comment]
@concretevitamin Just ran a benchmark with `crt` client. And it seems like setting the use for `crt` client affects the performance for `s5cmd` as well. Following is the comparison.

Sync on 1000 of 1MB files:
`aws s3 sync` with 10 threads with default client on 1000 of 1MB files: 20.738014650344848
`aws s3 sync` with 10 threads with crt client on 1000 of 1MB files: 22.9957523346
`s5cmd sync` with 10 threads with default client on 1000 of 1MB files 7.532667350769043
`s5cmd sync` with 10 threads with crt client on 1000 of 1MB files 4.55448350906372

Sync on 6 of 10GB files:
`aws s3 sync` with 10 threads with default client on 6 of 10GB files: 612.9618566036224
`aws s3 sync` with 10 threads with crt client on 6 of 10GB files: 412.372611364
`s5cmd sync` with 10 threads with default client on 6 of 10GB files: 386.55710673332214
`s5cmd sync` with 10 threads with crt client on 6 of 10GB files: 108.94380240440368

chatGPT generated graph:
image
image


A way to configure for the `crt` client is to run `aws s3 configure` command or set `~/.aws/config` in it. I can create a separte PR to add a doc to set this config for faster performance in case users wants it for either `aws s3 sync` or `s5cmd sync`.

**Comment by landscapepainter** [comment]
@romilbhardwaj `--include` is implemented. This is ready for another look!

**Comment by landscapepainter** [comment]
Need to add a setup for `crt `client at `~/.aws/config` of remote machine for faster fetch when provisioning.

**Comment by turian** [comment]
@romilbhardwaj @landscapepainter is this PR ready?

**Pull request closed without merging**
