### PR TITLE
Support multiple resources

### PR DESCRIPTION
**Pull request by infwinston**
This PR supports specifying multiple resources with SkyPilot's programatic API and a basic YAML interface.

Python example:
```
import sky

task = sky.Task(run='nvidia-smi')

task.set_resources({
    sky.Resources(sky.AWS(), zone='us-east-1d', use_spot=True, accelerators={'K80': 1}),
    sky.Resources(sky.GCP(), accelerators={'K80': 1}),
})

sky.launch(task, cluster_name=f'my-cluster', stream_logs=False, down=False)
sky.exec(task, cluster_name='my-cluster', stream_logs=True)
```

Console output
```
(sky-tmp) weichiang@mbp sky % python examples/multi_resources.py
I 11-10 16:31:03 optimizer.py:610] == Optimizer ==
I 11-10 16:31:03 optimizer.py:621] Target: minimizing cost
I 11-10 16:31:03 optimizer.py:633] Estimated cost: $0.3 / hour
I 11-10 16:31:03 optimizer.py:633]
I 11-10 16:31:03 optimizer.py:689] Considered resources (1 node):
I 11-10 16:31:03 optimizer.py:718] ----------------------------------------------------------------------
I 11-10 16:31:03 optimizer.py:718]  CLOUD   INSTANCE          vCPUs   ACCELERATORS   COST ($)   CHOSEN
I 11-10 16:31:03 optimizer.py:718] ----------------------------------------------------------------------
I 11-10 16:31:03 optimizer.py:718]  AWS     p2.xlarge[Spot]   4       K80:1          0.27          ✔
I 11-10 16:31:03 optimizer.py:718]  GCP     n1-highmem-4      4       K80:1          0.69
I 11-10 16:31:03 optimizer.py:718] ----------------------------------------------------------------------
I 11-10 16:31:03 optimizer.py:718]
I 11-10 16:31:03 cloud_vm_ray_backend.py:2790] Creating a new cluster: "my-cluster" [1x AWS(p2.xlarge[Spot], {'K80': 1})].
...
```
When AWS fails, we'll go to GCP.

YAML example
```
resources:
  cloud: aws
  use_spot: true
  accelerators: ['K80:1', 'V100:1']
```

TODO
- [x] basic YAML interface (a list of accelerators)
- [ ] Complicated YAML interface (should we do it?
- [x] ~~Add option to disable optimizer~~ honor user's preferred order when acc is list
- [ ] Grafana usage collection schema
- [ ] Smoke test

### CODE REVIEW

**Comment by concretevitamin** [comment]
@infwinston quick question, in our discussion IIRC we decided to not use sets, but use lists?
```
task.set_resources({
    sky.Resources(sky.AWS(), zone='us-east-1d', use_spot=True, accelerators={'K80': 1}),
    sky.Resources(sky.GCP(), accelerators={'K80': 1}),
})
```

**Comment by infwinston** [comment]
Yes, I'm adding the list support now and will update the PR soon. This will require some changes in our optimizer logic. It'd be nice if @WoosukKwon can help to take a look as I'm not sure if this would be a conflict with the resource refactoring PR.

**Comment by Michaelvll** [comment]
This has been asked by multiple users. We might want to keep it open. cc @infwinston

**Comment by Michaelvll** [comment]
This should be fixed by #2498. Let's close this one : )

**Pull request closed without merging**
