### PR TITLE
Pin flax version to fix tpu example

### PR DESCRIPTION
**Pull request by infwinston**
Fixes https://github.com/skypilot-org/skypilot/issues/2469. Tested on `tpu-v2-8` and `tpu-v2-32`.

Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by infwinston** [comment]
@cblmemo let me know if this fixes your smoke test!

**Review by cblmemo — COMMENTED** [review]
It works for me! Just a question: I'm thinking maybe we could clone the GitHub repo with some tags (like version == 0.6.11) rather than using pip to install it, so we don't need to clone it again from pip. Does that sound good to you?

**Comment by infwinston** [comment]
ah the `git clone` is needed because we need to run the example in the flax repo..

**Comment by cblmemo** [comment]
> ah the `git clone` is needed because we need to run the example in the flax repo..

Yeah, so I was wondering if we could install flax through the cloned repo?

**Comment by infwinston** [comment]
> Yeah, so I was wondering if we could install flax through the cloned repo? Maybe specify some commit hash or tag when cloning? (If it is not too hard)

oh I see. let me do it.

**Review by cblmemo — APPROVED** [review]
Just tested and it works great! Thanks for fixing this ;)

**Pull request merged**
