### PR TITLE
AWS: support custom instance tags in ~/.sky/config.yaml.

### PR DESCRIPTION
**Pull request by concretevitamin**
To use this, write to `~/.sky/config.yaml`:
```
aws:
  # Tags (key-value pairs) to assign to all instances launched by SkyPilot for
  # this cloud.
  #
  # Users should guarantee that these key-values are valid AWS tags, otherwise
  # errors from the cloud provider will be surfaced.
  instance_tags:
    my-tag-1: my-value-1
    my-tag-2: my-value-2
    tag with spaces: my-value
    value-with-spaces: my value
```
Screen Shot 2023-05-27 at 15 48 07

Tested (run the relevant ones):

- [x] Any manual or new tests for this PR (please specify below)
  - Good case above
  - Bad case: a key with 129 characters (1 above limit)
    - This triggers failover with errors in each region `create_instances: Attempt failed with An error occurred (InvalidParameterValue) when calling the RunInstances operation: Tag key exceeds the maximum length of 128 characters, retrying.`
    - [ ] TODO: We can optimize this in the future
  - Back compat: `sky launch` on a previously autostopped cluster with new tags specified
    - Observed that new tags are not applied to old cluster (expected)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by Michaelvll** [comment]
Just a quick question, do we want to have it in the global config or the task specification instead? I am wondering if the user would like to have different tag for different tag.

**Comment by concretevitamin** [comment]
Yes, confirmed with user. The use case is to specify a constant
non-changing KV pair for all instances across all users, for discount
accounting purposes.

**Review by Michaelvll — APPROVED** [review]
Thanks for adding this feature in such a short time @concretevitamin! LGTM. It should be good to go in, if the tests are passed.

**Comment by concretevitamin** [comment]
Tested:

* Good case above
* Bad case: a key with 129 characters (1 above limit)  
  * This triggers failover with errors in each region `create_instances: Attempt failed with An error occurred (InvalidParameterValue) when calling the RunInstances operation: Tag key exceeds the maximum length of 128 characters, retrying.`
  * [ ]  TODO: We can optimize this in the future
* Back compat: `sky launch` on a previously autostopped cluster with new tags specified
  
  * Observed that new tags are not applied to old cluster (expected)

**Pull request merged**
