### PR TITLE
[Tests] Fix `test_jobs`

### PR DESCRIPTION
**Pull request by cblmemo**
Test `test_jobs.py` will fail on the current master:

```bash
(sky-dev) ➜  skypilot git:(master) ✗ pytest tests/test_jobs.py
bringing up nodes...
F.
================================================================================= FAILURES ==================================================================================
_____________________________________________________________ TestExecutionOnExistingClusters.test_launch_exec ______________________________________________________________
[gw0] linux -- Python 3.7.16 /home/memory/install/miniconda3/envs/sky-dev/bin/python
tests/test_jobs.py:86: in test_launch_exec
    sky.launch(task, cluster_name='test-cluster1', dryrun=True)
sky/utils/common_utils.py:332: in _record
    return f(*args, **kwargs)
sky/utils/common_utils.py:332: in _record
    return f(*args, **kwargs)
sky/execution.py:493: in launch
    _is_launched_by_spot_controller=_is_launched_by_spot_controller,
sky/execution.py:320: in _execute
    retry_until_up=retry_until_up)
sky/utils/common_utils.py:332: in _record
    return f(*args, **kwargs)
sky/utils/common_utils.py:311: in _record
    return f(*args, **kwargs)
sky/backends/backend.py:57: in provision
    cluster_name, retry_until_up)
sky/backends/cloud_vm_ray_backend.py:2820: in _provision
    task, to_provision_config, dryrun, stream_logs)
sky/utils/common_utils.py:332: in _record
    return f(*args, **kwargs)
sky/backends/cloud_vm_ray_backend.py:2217: in provision_with_retries
    ), prev_cluster_status
E   AssertionError: ClusterStatus.UP
========================================================================== short test summary info ==========================================================================
FAILED tests/test_jobs.py::TestExecutionOnExistingClusters::test_launch_exec - AssertionError: ClusterStatus.UP
1 failed, 1 passed, 16 warnings in 16.17s
```

It is due to no quota in AWS `us-east-1`, which will raise an `ResourcesUnavailableError` exception to interrupt the unittest. This PR fixed this bug.

Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by cblmemo** [comment]
TODO: investigate why our CI doesn't detect this error.

**Comment by cblmemo** [comment]
The reason the current CI doesn't detect this error: there are no credential files in CI's environment. It will throw an error in 
https://github.com/skypilot-org/skypilot/blob/734cf689e7b9e70bfce7d5dd9662472de2450aac/sky/backends/cloud_vm_ray_backend.py#L1447-L1455
And therefore we still need to provision since the zero quota optimization cannot determine whether there is quota.
Some outputs:
```bash
[botocore.exceptions.NoCredentialsError] Unable to locate credentials
```
Therefore,

**Comment by cblmemo** [comment]
@Michaelvll The reason why our CI doesn't detect this error is shown above. PTAL 😉

**Comment by Michaelvll** [comment]
If the quota check is the issue, should we directly monkey patch the quota checking function in the `conftest` to always return True?

**Comment by cblmemo** [comment]
> If the quota check is the issue, should we directly monkey patch the quota checking function in the `conftest` to always return True?

It is already always returning True (i.e. need provision) now since it cannot determine quota (since there is no credential).

**Comment by cblmemo** [comment]
> If the quota check is the issue, should we directly monkey patch the quota checking function in the `conftest` to always return True?

Good idea! Let me do this 🫡

**Review by Michaelvll — APPROVED** [review]
Thanks for the fix @cblmemo! LGTM.

**Pull request merged**
