### PR TITLE
os.devnull usages in Windows fix, and Temporarily disable TextWrapper register in log_lib #1950

### PR DESCRIPTION
**Pull request by aria1th**
https://github.com/skypilot-org/skypilot/issues/1950

In Windows, we can't use anything like `nul/something`, if it happens, the path is '' (empty string) and os related python functions will throw WinError.

This Pull Request just solves those simple cases, by just fallbacking to os.devnull again.

This also tries to solve Socket related selector Error, caused by TextIOWrapper usage.

Unfortunately, Windows environment is not fully solved yet, it now tries to use directory name of current file before creating or checking it in remote side, causing No such file or directory. 

Tested (run the relevant ones):

- [x] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`
- [x] Codespaces test for linux environments
- [x] Windows 10 Environments

Test Code:
```py
import runhouse as rh
def num_cpus():
    import multiprocessing
    return multiprocessing.cpu_count()

# #1950 issue, this won't start up and throw WinError 3 or WinError 10038 without patch.
cluster = rh.cluster(
    name = "test",
    ips = ['private-ip'],
    ssh_creds = {
        'ssh_user': 'serveradmin',
        'ssh_private_key': r'C:\.... .rsa'
    }
)

# New issue, more headaches
num_cpus_cluster = rh.function(
    name = "num_cpus_cluster",
    fn = num_cpus
).to(cluster)



print(num_cpus_cluster())
```

### CODE REVIEW

**Comment by romilbhardwaj** [comment]
Thanks for creating this PR @aria1th. SkyPilot currently does not support Windows natively, and we recommend using WSL to run SkyPilot on Windows devices. 

If I understand correctly, this PR is trying to fix SkyPilot to work on Windows natively. I'm happy to help with this effort.

I tried running your branch (and master) on my Windows machine and ran into this YAML parsing error before I could get to testing your fix. Did you also run into this error? Just want to confirm if it's my environment or something you also had to fix but didn't include in the PR.

```
C:\Romil\cmder
λ sky launch --cpus 4
I 05-18 23:31:59 optimizer.py:636] == Optimizer ==
I 05-18 23:31:59 optimizer.py:647] Target: minimizing cost
I 05-18 23:31:59 optimizer.py:659] Estimated cost: $0.2 / hour
I 05-18 23:31:59 optimizer.py:659]
I 05-18 23:31:59 optimizer.py:732] Considered resources (1 node):
I 05-18 23:31:59 optimizer.py:781] -----------------------------------------------------------------------------------------
I 05-18 23:31:59 optimizer.py:781]  CLOUD   INSTANCE     vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 05-18 23:31:59 optimizer.py:781] -----------------------------------------------------------------------------------------
I 05-18 23:31:59 optimizer.py:781]  AWS     m6i.xlarge   4       16        -              us-east-1     0.19          ✔
I 05-18 23:31:59 optimizer.py:781] -----------------------------------------------------------------------------------------
I 05-18 23:31:59 optimizer.py:781]
Launching a new cluster 'sky-4645-romilbhardwaj'. Proceed? [Y/n]: Y
I 05-18 23:32:00 cloud_vm_ray_backend.py:3423] Creating a new cluster: "sky-4645-romilbhardwaj" [1x AWS(m6i.xlarge)].
I 05-18 23:32:00 cloud_vm_ray_backend.py:3423] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 05-18 23:32:01 cloud_vm_ray_backend.py:1202] To view detailed progress: tail -n100 -f C:\Users\romil_bhardwaj/sky_logs\sky-2023-05-18-23-31-57-698087\provision.log
Traceback (most recent call last):
  File "C:\Romil\skypilot\sky\execution.py", line 266, in _execute
    handle = backend.provision(task,
  File "C:\Romil\skypilot\sky\utils\common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "C:\Romil\skypilot\sky\utils\common_utils.py", line 220, in _record
    return f(*args, **kwargs)
  File "C:\Romil\skypilot\sky\backends\backend.py", line 56, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "C:\Romil\skypilot\sky\backends\cloud_vm_ray_backend.py", line 2278, in _provision
    config_dict = provisioner.provision_with_retries(
  File "C:\Romil\skypilot\sky\utils\common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "C:\Romil\skypilot\sky\backends\cloud_vm_ray_backend.py", line 1776, in provision_with_retries
    config_dict = self._retry_zones(
  File "C:\Romil\skypilot\sky\backends\cloud_vm_ray_backend.py", line 1249, in _retry_zones
    config_dict = backend_utils.write_cluster_config(
  File "C:\Romil\skypilot\sky\utils\common_utils.py", line 241, in _record
    return f(*args, **kwargs)
  File "C:\Romil\skypilot\sky\backends\backend_utils.py", line 915, in write_cluster_config
    _add_auth_to_cluster_config(cloud, tmp_yaml_path)
  File "C:\Romil\skypilot\sky\backends\backend_utils.py", line 990, in _add_auth_to_cluster_config
    config = common_utils.read_yaml(cluster_config_file)
  File "C:\Romil\skypilot\sky\utils\common_utils.py", line 173, in read_yaml
    config = yaml.safe_load(f)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 572, in parse_flow_mapping_value
    if not self.check_token(FlowEntryToken, FlowMappingEndToken):
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "C:\Users\romil_bhardwaj\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\romil_bhardwaj\.sky\generated\sky-4645-romilbhardwaj.yml.tmp", line 81, column 25
expected escape sequence of 8 hexdecimal numbers, but found 's'
  in "C:\Users\romil_bhardwaj\.sky\generated\sky-4645-romilbhardwaj.yml.tmp", line 81, column 30
```

**Comment by aria1th** [comment]
@romilbhardwaj No, I had an another error because I were testing with BYO cluster(dedicated server)

The issue seems like auto generated yaml contains option "/path/continued"
But in native windows, seems like it allows escaping with backslashes when its read.

Thus we need
'/path/continued'
Or
r"path/continued"
In autogenerated YAML file.

**Comment by romilbhardwaj** [comment]
Yes, I believe that should fix it. Can we include this fix for YAML writing/parsing in this PR?

**Comment by aria1th** [comment]
@romilbhardwaj I suspect the YAML issue is from [here](https://github.com/skypilot-org/skypilot/blob/master/sky/templates/aws-ray.yml.j2#L146) , which is auto filled with jinja2.

I expect more bunch of errors in windows, but can you try with https://github.com/aria1th/skypilot/tree/test-abspath ?

**Pull request closed without merging**
