### PR TITLE
Fix unnecessary ssh hanging issue on Ray

### PR DESCRIPTION
**Pull request by infwinston**
This PR aims to fix https://github.com/sky-proj/sky/issues/849 by patching Ray autoscaler. Detailed explained in the issue.

We think a simple way is to patch Ray's autoscaler by adding

`self.provider.non_terminated_nodes({})`
before https://github.com/ray-project/ray/blob/6d978ab10ec65da1018790f8605b5b8946e838e5/python/ray/autoscaler/_private/updater.py#L272.

`non_terminated_nodes()` will refresh the states of `self.cached_nodes` and then ray will be able to detect whether the VM is terminated during ssh retry.

----

Regarding testing this PR, unfortunately https://github.com/sky-proj/sky/issues/849 is a little bit hard to reproduce. I tried to manually terminate the VM but this way there won't be gap between VM shutting down and VM state being RUNNING. Not sure if we can simulate preemption signals.

### CODE REVIEW

**Comment by Michaelvll** [comment]
Is this still a problem after PR #969 was merged @infwinston ?

**Comment by infwinston** [comment]
I've tested the patch and it works well. before all my spot TPU preemption requires 15mins to recover, with this it becomes 5mins.
I'll update code line number after https://github.com/skypilot-org/skypilot/pull/1133 is merged.

**Review by Michaelvll — APPROVED** [review]
LGTM! Thanks @infwinston! Can we also manually check the `updater.py` file on the remote VM to make sure the file is updated correctly before merging?

**Comment by infwinston** [comment]
Yes I checked before and now again. it's patched at the correct place. merging now.

**Pull request merged**
