### PR TITLE
[k8s_cloud_beta1] Add minio object store support.

### PR DESCRIPTION
**Pull request by aviweit**
We have an on-prem installation of minio object store, which is S3 compatible. We had been able to add minio support to SkyPilot and test it against our local installation with Kubernetes (`kubeadm` based and `kind`).

We added example tasks under `examples/storage/minio` and updated `tests/test_smoke.py` that can be invoked via:

```
pytest -v tests/test_smoke.py  --generic-cloud kubernetes -m minio --minio
```

Please find below a setup example:

1. Start minio container: 

```
docker run -p 9000:9000 -d -p 9001:9001 -e "MINIO_ROOT_USER=minio99" -e "MINIO_ROOT_PASSWORD=minio123" quay.io/minio/minio server /data --console-address ":9001"
```

2. Loginto minio web ui (localhost port 9001) with above minio root user/password. Select Access Key at left pane and generate it.

3. Create ~/.sky/config.yaml with minio endpoint:
```
    minio:
        endpoint: "http://<your minio host name>:9000"
```

4. Invoke AWS CLI to set access and secretes keys (generated in the step above). For rest prompts - enter defaults.
```
AWS_SHARED_CREDENTIALS_FILE=~/.minio/minio.credentials aws configure --profile minio
```

5. Invoke `sky check`. Kubernetes and minio should pass.

### CODE REVIEW

**Comment by aviweit** [comment]
Hi @romilbhardwaj , @landscapepainter , can you please review this PR?
Thanks.

**Review by landscapepainter — COMMENTED** [review]
@aviweit Thanks for adding the support for `minio`. This is absolutely in my priority list and I'll get on to reviewing perhaps starting later this week.

**Comment by landscapepainter** [comment]
> Should it be `num_objects > 1` ?

You are correct and thanks for catching this. I manually tried out for some examples and we should fix this to `num_objects > 1`.

**Comment by aviweit** [comment]
Hi, running:

'pytest -v tests/test_smoke.py  --generic-cloud kubernetes -m minio --minio'

returned with:

```
== short test summary info==
FAILED tests/test_smoke.py::TestStorageWithCredentials::test_invalid_names[invalid_name_list4-StoreType.MINIO] - ValueError: Storage ab not found.
== 1 failed, 9 passed, 1590 warnings in 124.81s (0:02:04) ==
```

**Comment by romilbhardwaj** [comment]
Thanks for adding this @aviweit. One key thing to think about before we merge this is how do we handle MinIO accesses from outside the Kubernetes cluster. In SkyPilot, this can happen in two situations:

1. When user specifies a local `source` path to upload files to the remote object store
2. When task spills over from the Kubernetes cluster to a public cloud/another kubernetes cluster.

For 1), their [docs](https://min.io/docs/minio/kubernetes/upstream/index.html) uses `kubectl port-forward`. We will need to support this in our storage upload codepaths. For 2), I don't know a generally applicable solution. We may need to add some filtering to task spillover (e.g., through `CloudImplementationFeatures`?) to prevent tasks with MinIO requirements to spill over to public clouds, but I'm not fully sure what the interfaces look like here.

**Comment by aviweit** [comment]
Hi @romilbhardwaj , currently, MinIO endpoint, which is defined inside `~/.sky/config.yaml`, for example:

```
    minio:
        endpoint: "http://10.100.200.3:9000"
```

is assumed to be externally accessible from user laptop and Kubernetes (e.g. ray cluster).

In our environment, 10.100.200.3, is an on-prem VM ipaddress inside our intranet where our laptops and k8s clusters are connected to.

**Pull request closed without merging**
