### PR TITLE
[Onprem] Enable admin to launch Ray cluster

### PR DESCRIPTION
**Pull request by michaelzhiluo**
This PR looks to make Sky Onprem deployment easier for users and admin. Launching the Ray cluster from the root user (using `sudo`) raised various installation bugs (reported by @WoosukKwon and @Michaelvll ) and various dependency versioning issues (reported by @Michaelvll ). Moving the Ray cluster to be launched by the admin instead solves all of this.

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@concretevitamin @romilbhardwaj Can one of you also review the 3 on-prem PRs? As it's not first time looking at the on-prem code, I might not be a good/quick reviewer. I will review the PRs in parallel with you.

**Comment by concretevitamin** [comment]
@WoosukKwon No problem - Romil is probably the most knowledgeable with this code. I was thinking if you could help with testing these PRs (may need to merge all into a branch) to see if they solve deployment problems.

**Comment by romilbhardwaj** [comment]
This is awesome! Setting up on ec2linux was a breeze with this and I was able to successfully run a task as the admin user (`ec2-user`).

However, there seem to be some issues with multi-tenancy. I failed to run jobs as a different user.

I setup another user by sshing into the VM:
```
sudo adduser --disabled-password --gecos '' test
sudo -H su test -c 'mkdir ~/.ssh'
sudo -H su test -c 'chmod 700 ~/.ssh'
sudo -H su test -c 'touch ~/.ssh/authorized_keys'
sudo -H su test -c 'chmod 600 ~/.ssh/authorized_keys'
sudo -H su test -c 'echo KEY > ~/.ssh/authorized_keys'
```

I then edited my ~/.sky/local/myclus.yaml to use `test` user in the `auth` field. I then tried to launch minimal.yaml but that failed:
```
Task from YAML spec: minimal.yaml
I 08-26 19:31:09 optimizer.py:605] == Optimizer ==
I 08-26 19:31:09 optimizer.py:628] Estimated cost: $0.0 / hour
I 08-26 19:31:09 optimizer.py:628]
I 08-26 19:31:09 optimizer.py:685] Considered resources (1 node):
I 08-26 19:31:09 optimizer.py:713] ---------------------------------------------------------------
I 08-26 19:31:09 optimizer.py:713]  CLOUD   INSTANCE   vCPUs   ACCELERATORS   COST ($)   CHOSEN
I 08-26 19:31:09 optimizer.py:713] ---------------------------------------------------------------
I 08-26 19:31:09 optimizer.py:713]  Local   on-prem    -       -              0.00          ✔
I 08-26 19:31:09 optimizer.py:713] ---------------------------------------------------------------
I 08-26 19:31:09 optimizer.py:713]
Initializing local cluster 'onprem2'. Proceed? [Y/n]: Y
I 08-26 19:31:10 cloud_vm_ray_backend.py:2598] Connecting to local cluster: 'onprem2' [Username: test].
I 08-26 19:31:10 cloud_vm_ray_backend.py:2598] Run `sky status` to see existing clusters.
I 08-26 19:31:10 cloud_vm_ray_backend.py:892] To view detailed progress: tail -n100 -f /home/romilb/sky_logs/sky-2022-08-26-19-31-09-157480/provision.log
I 08-26 19:31:11 cloud_vm_ray_backend.py:1092] Launching on local cluster 'onprem2'.
I 08-26 19:31:16 log_utils.py:45] Head node is up.
I 08-26 19:31:25 cloud_vm_ray_backend.py:1910] Running setup on 1 node.
I 08-26 19:31:26 cloud_vm_ray_backend.py:1913] Setup completed.
I 08-26 19:31:29 cloud_vm_ray_backend.py:1978] Job submitted with Job ID: 2
I 08-27 02:31:31 log_lib.py:376] Start streaming logs for job 2.
INFO: Tip: use Ctrl-C to exit log streaming (task will not be killed).
INFO: Waiting for task resources on 1 node. This will block if the cluster is full.
INFO: All task resources reserved.
INFO: Reserved IPs: ['172.31.43.227']
Traceback (most recent call last):
  File "/home/test/.sky/sky_app/sky_job_2", line 368, in <module>
    returncodes = ray.get(futures)
  File "/home/test/.local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/ray/util/client/api.py", line 44, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/test/.local/lib/python3.7/site-packages/ray/util/client/worker.py", line 438, in get
    res = self._get(to_get, op_timeout)
  File "/home/test/.local/lib/python3.7/site-packages/ray/util/client/worker.py", line 466, in _get
    raise err
types.RayTaskError(PermissionError): ray::minimal (pid=7496, ip=172.31.43.227)
  File "/home/test/.sky/sky_app/sky_job_2", line 311, in run_bash_command_with_log
  File "/home/test/.sky/sky_app/sky_job_2", line 231, in run_with_log
  File "/home/test/.sky/sky_app/sky_job_2", line 64, in process_subprocess_stream
PermissionError: [Errno 13] Permission denied: '/home/test/sky_logs/sky-2022-08-26-19-31-09-157480/tasks/run.log'

^CW 08-26 19:31:59 backend_utils.py:1780] The job will keep running after Ctrl-C.
Shared connection to 54.186.202.57 closed.
I 08-26 19:31:59 cloud_vm_ray_backend.py:1991] Job ID: 2
I 08-26 19:31:59 cloud_vm_ray_backend.py:1991] To cancel the job:       sky cancel onprem2 2
I 08-26 19:31:59 cloud_vm_ray_backend.py:1991] To stream the logs:      sky logs onprem2 2
I 08-26 19:31:59 cloud_vm_ray_backend.py:1991] To view the job queue:   sky queue onprem2
I 08-26 19:31:59 cloud_vm_ray_backend.py:2100]
I 08-26 19:31:59 cloud_vm_ray_backend.py:2100] Cluster name: onprem2
I 08-26 19:31:59 cloud_vm_ray_backend.py:2100] To log into the head VM: ssh onprem2
I 08-26 19:31:59 cloud_vm_ray_backend.py:2100] To submit a job:         sky exec onprem2 yaml_file
I 08-26 19:31:59 cloud_vm_ray_backend.py:2100] To teardown the cluster: sky down onprem2
No existing clusters.

Local clusters:
NAME          USER  HEAD_IP        RESOURCES    COMMAND
onprem2       test  54.186.202.57  [(no GPUs)]  sky launch -c onprem2 min...
```

My hunch is that the logs are written as the admin user, which prevents the `test` user from reading them. I tried `chmod -R 777 ~/sky_logs` but that did not help.

If we can fix this bug, this would be an awesome solution to our deployment problems!

**Comment by michaelzhiluo** [comment]
@romilbhardwaj Just fixed a bug regarding this Pr, the following commands/steps should work:
1) Launching a cluster via Sky
2) Setting up Admin YAML w.r. to that cluster
3) `sky admin deploy ...`

**Review by romilbhardwaj — APPROVED** [review]
Works nicely now! Just tested on aws ubuntu deep learning AMI with both, `ubuntu` user and a custom user I created (as I mentioned in my previous comment). Ready to 🚢!

**Pull request merged**
