### PR TITLE
[Usage] Robustify the user hash to avoid empty string

### PR DESCRIPTION
**Pull request by Michaelvll**
This PR is to robustify the user hash, to avoid getting empty user hash from the file. It could happen before when the program crashed before writing to the file.
https://github.com/skypilot-org/skypilot/blob/48d4a84865821b468d0a608ef4860d7f352859f0/sky/utils/common_utils.py#L55-L56

### CODE REVIEW

**Review by concretevitamin — APPROVED** [review]

**Comment by Michaelvll** [comment]
I changed the check for valid user hash by checking it is a valid hex-decimal and has a length of 8, to avoid any invalid characters appearing in the result.

**Review by concretevitamin — APPROVED** [review]
LGTM.  Question: why cache the hash in a file instead of re-computing; for speed?

**Comment by Michaelvll** [comment]
> LGTM. Question: why cache the hash in a file instead of re-computing; for speed?

That is to avoid the problem caused by changing the username. Previously, one of our users changed her username, causing the spot controller and other user hashes change.

**Comment by concretevitamin** [comment]
Ah, I see, worth a comment!

**Pull request merged**
