### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by Michaelvll**
- [x] `pytest tests/test_smoke.py` (commit: 92b2e118a589f24b82a28)
- [x] `pytest tests/test_smoke.py --aws` (~~except for `test_aws_custom_image` being fixed in #3215~~)
- [x] `pytest tests/test_smoke.py --gcp`
- [x] `pytest tests/test_smoke.py --azure` (~~except for `test_job_queue_with_docker` being fixed in #3218~~)
- [x] `pytest tests/test_smoke.py --kubernetes`
- [x] locally build docs, open `docs/build/index.html`, scroll over “CLI Reference” (ideally, every page) to see if there are missing sections (we once caught the CLI page completely missing due to an import error; and once it has weird blockquotes displayed)
- [x] Check `sky -v`
- [x] `backward_compatibility_tests.sh` run against 0.4.1 on aws
- [x] `backward_compatibility_tests.sh` run against 0.4.1 on gcp
- [x] Run manual stress tests (see subsection below)
   - [x] following script
        ```
        sky spot launch --gpus A100:8 --cloud aws echo hi -y
        # Check we are properly failing over the zones:
        sky spot logs --controller
        ```
  - [x] following script (skipped, not enough quotas)
    ```
    sky launch -c dbg --cloud aws --num-nodes 16 --gpus T4 --down --use-spot 
    sky down dbg
    ```
  - [x] `sky launch --num-nodes=75 -c dbg --cpus 2+ --use-spot --down --cloud gcp -y`
  - [x] `sky launch --num-nodes=75 -c dbg --cpus 2+ --use-spot --down --cloud aws -y`

### CODE REVIEW

**Comment by concretevitamin** [comment]
Is test_aws_custom_image related to #3213?

**Comment by Michaelvll** [comment]
> Is test_aws_custom_image related to #3213?

it seems to be related to #3215. Will get that merged soon : )

**Review by romilbhardwaj — APPROVED** [review]
Thanks @Michaelvll 🎉

**Review by concretevitamin — APPROVED** [review]
LGTM!

**Pull request merged**
