### PR TITLE
[Controllers] Use local catalog for controllers

### LINKED ISSUE #3260: Failed to register SkyServe controller on non US Azure region
Hello,

When I did a `sky serve up`, after having only `francecentral` azure region into the catalog (like described in the [FAQ](https://skypilot.readthedocs.io/en/latest/reference/faq.html#advanced-how-to-make-skypilot-use-all-global-regions)), I succeed to provision on francecentral region, but when the job is submitted, I got an error saying the region is invalid.

Please find an extract of the logs

```
I 03-01 12:02:08 cloud_vm_ray_backend.py:1763] Launching on Azure francecentral
I 03-01 12:03:43 log_utils.py:45] Head node is up.
I 03-01 12:04:46 cloud_vm_ray_backend.py:1611] Successfully provisioned or found existing VM.
I 03-01 12:04:48 cloud_vm_ray_backend.py:4275] Processing file mounts.
I 03-01 12:04:48 cloud_vm_ray_backend.py:4307] To view detailed progress: tail -n100 -f ~/sky_logs/sky-2024-03-01-12-02-07-802222/file_mounts.log
I 03-01 12:04:48 backend_utils.py:1272] Syncing (to 1 node): /tmp/service-task-sky-service-569a-llfl2uf9 -> ~/.sky/serve/sky_service_569a/task.yaml.tmp
I 03-01 12:04:49 cloud_vm_ray_backend.py:3085] Running setup on 1 node.
I 03-01 12:04:58 cloud_vm_ray_backend.py:3098] Setup completed.
I 03-01 12:05:03 cloud_vm_ray_backend.py:3180] Job submitted with Job ID: 2

E 03-01 12:06:05 subprocess_utils.py:84] ValueError: Failed to register service 'sky-service-569a' on the SkyServe controller. Reason:
E 03-01 12:06:05 subprocess_utils.py:84] ValueError: Invalid region 'francecentral'
E 03-01 12:06:05 subprocess_utils.py:84] If a region is not included in the following list, please check the FAQ docs for how to fetch its catalog info.
E 03-01 12:06:05 subprocess_utils.py:84] https://skypilot.readthedocs.io/en/latest/reference/faq.html#advanced-how-to-make-skypilot-use-all-global-regions
E 03-01 12:06:05 subprocess_utils.py:84] List of supported azure regions: 'centralus, eastus, eastus2, northcentralus, southcentralus, westcentralus, westus, westus2, westus3'
E 03-01 12:06:05 subprocess_utils.py:84] 
E 03-01 12:06:05 subprocess_utils.py:84] 
RuntimeError: Failed to spin up the service. Please check the logs above for more details.
```

### PR DESCRIPTION
**Pull request by romilbhardwaj**
Closes #3260, #3165.

Adds local catalog sync to controller.

The catalog dir is ~3 MB, and adds about 2.3s for provisioning. Thinking as a future optimization, we can sync catalog only if changes are detected in local catalog (this optimization assumes downloading catalog from github will be faster than uploading from local laptop). 

Tested manually by removing all regions except asia-east1 for T4 on GCP and running `sky serve up` and `sky spot launch` with the following YAML:

```
service:
  readiness_probe:
    path: /health
    initial_delay_seconds: 20
  replicas: 2

resources:
  ports: 8081
  cpus: 1+
  accelerators: T4:1
  cloud: gcp

setup: |
  git clone https://www.github.com/skypilot-org/skypilot.git

run: |
  cd skypilot/examples/serve/http_server
  python3 server.py
```

### CODE REVIEW

**Review by Michaelvll — COMMENTED** [review]
Thanks for adding this to make the catalog in sync for controller and local @romilbhardwaj! Is it possible to just do the catalog uploading when a user manually changed file to avoid increasing the time for running a spot job/service, as the the file mounts in the critical path of launching spot jobs and users have asking for speeding up submitting multiple spot jobs #3190?

**Comment by romilbhardwaj** [comment]
Updated the catalog upload logic to upload only the catalogs which have been modified locally. Ready for another look!

- [x] Tested manually with the yaml in the PR description
- [ ] Smoke tests

**Review by Michaelvll — APPROVED** [review]
Thanks for fixing this @romilbhardwaj! LGTM. Please add `paperspace` in `ALL_CLOUDS` : )

**Comment by romilbhardwaj** [comment]
Thanks @Michaelvll - addressed comments and ran some manual tests to verify it still works. Merging now!

**Pull request merged**
