### PR TITLE
[Storage] Adding new storage mode C_SYNC

### LINKED ISSUE #1862: [Storage] Periodic local folder/bucket syncing for better performance
Instead of using the mounted storage, in our [Vicuna example](https://github.com/skypilot-org/skypilot/blob/master/llm/vicuna/train.yaml), we manually run a [script](https://github.com/lm-sys/FastChat/blob/main/scripts/sync_local_checkpoint.sh) to periodically sync a local disk with a folder in the mounted storage using `gsutil -m rsync` for the model checkpoints which is much faster than directly saving the checkpoint to the mounted storage. We must think of a way to integrate this logic into the SkyPilot Storage. 

```
#!/bin/bash

local_path=$1
remote_path=$2
MAX_NUM_CKPT=3

# This script is used to periodically copy local checkpoint to mounted storage
while true; do
    local_last_ckpt=$(ls ${local_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | tail -1)
    remote_last_ckpt=$(ls ${remote_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | tail -1)
    echo "local_last_ckpt: ${local_last_ckpt}"
    echo "remote_last_ckpt: ${remote_last_ckpt}"
    if [ "${local_last_ckpt}" != "${remote_last_ckpt}" ]; then
        mkdir -p ${remote_path}/${local_last_ckpt}
        gsutil -m rsync -r ${local_path}/${local_last_ckpt}/ ${remote_path}/${local_last_ckpt}

        # Keep only the last MAX_NUM_CKPT checkpoints
        num_local_ckpt=$(ls ${local_path} | grep checkpoint- | wc -l)
        echo "num_local_ckpt: ${num_local_ckpt}"
        if [ ${num_local_ckpt} -gt $MAX_NUM_CKPT ]; then
            for ckpt in $(ls ${local_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | head -n-${MAX_NUM_CKPT}); do
                rm -rf ${local_path}/${ckpt}
            done
        fi
    fi

    sleep 600
done
```

Several things to do for the sync:
1. Upload the checksum for the checkpoint folder first, to make sure the corrupted checkpoints are not used when recovered from the preemptions
2. Need to think of the way for the API we provide. The script above assumes the checkpoints folders have specific structure, i.e.
```
CKPT_PATH/
  - checkpoint-1000/
  - checkpoint-2000/
...
```

### PR DESCRIPTION
**Pull request by landscapepainter**
This closes #1862 

When using managed spot job for training, it's necessary to save the checkpoints in the cloud storage as we want the training to recover from the checkpoint when preempted. And this requires the application to store the checkpoints in the cloud storage. However, writing the checkpoints to a cloud storage mounted directory takes a long time, especially for large models like LLM, and this stalls the training becoming the bottleneck. 

To mitigate this issue, this PR adds a new storage mode, `C_SYNC`, where it runs a daemon to run syncing commands periodically at the specified remote path. This way, the training application can write the checkpoints to an unmounted directory and the checkpoints get synced asynchronously., which makes the process much quicker.

When a cluster running sync command laucnhed by `csync` is attempted to be stopped with `sky stop`/`sky down`, then it waits until the sync is completed before proceeding to stop/down the cluster.

**Note:**

- Running `backend_utils.wait_and_terminate_csync()` within `cli.py/_down_or_stop()` can be implemented smoothly with storage info in cluster table's metadata. Will implement this in a separate [issue](https://github.com/skypilot-org/skypilot/issues/2278)
- `backend_utils.wait_and_terminate_csync()` does not support `autostop`/`autodown` yet. Will be implemented after this [PR](https://github.com/skypilot-org/skypilot/pull/2248) is merged

**TODO:**
- [x] write `_execute_storage_syncs` to setup `mode: C_SYNC`
- [x] Handle `sky stop`/`down`/`autostop`/`autodown` with `cluster`'s `metadata`
- [x] support for user specifying syncing interval in task yaml
- [x] write the continuous syncing as an independent tool
- [x] add sync command for s3 and gcs
- [x] add storage tests for `mode: C_SYNC`

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [x] Manual test on running `C_SYNC` mode
- [x] Manual test to run `sky stop` on a cluster running sync command launched by `csync`
- [x] Test managed spot job with checkpoint directory in `C_SYNC` mode to confirm if training recovers correctly from checkpoints.
- [x] Relevant individual smoke tests: `pytest tests/test_smoke.py::TestStorageWithCredentials` 
- [x] `pytest tests/test_smoke.py::test_aws_storage_mounts --aws` 
- [x] `pytest tests/test_smoke.py::test_gcp_storage_mounts --gcp`

### CODE REVIEW

**Comment by Michaelvll** [comment]
I am trying out this on the vicuna/llama-2 PR, and it seems `rm` a folder in the C_SYNC directory will not be reflected to the bucket. Is that expected? That may cause the HF trainer failed to remove the older checkpoints from the bucket.

**Comment by landscapepainter** [comment]
> it seems `rm` a folder in the C_SYNC directory will not be reflected to the bucket.

There was an error occurring that `csync` process would self-terminate when `gsutil` uploading ckpts to bucket from mount point(`/artifacts`) and the training script writing ckpts to the mount point was occurring at the same time. This is resolved in my new commit, which seems to not being reflected in this PR. As the PR seems broken I re-opened the PR to have the change reflected #2336. Please try out this branch.

Regarding to the log, it is yet to be implemented. Temporary solution I used to check the log was to redirect the output of the `sync` process by changing `L97` from `sky/data/skystorage.py` so that it outputs to a local log file.

**Comment by Michaelvll** [comment]
> > it seems `rm` a folder in the C_SYNC directory will not be reflected to the bucket.
> 
> There was an error occurring that `csync` process would self-terminate when `gsutil` uploading ckpts to bucket from mount point(`/artifacts`) and the training script writing ckpts to the mount point was occurring at the same time. This is resolved in my new commit, which seems to not being reflected in this PR. As the PR seems broken I re-opened the PR to have the change reflected #2336. Please try out this branch.
> 
> Regarding to the log, it is yet to be implemented. Temporary solution I used to check the log was to redirect the output of the `sync` process by changing `L97` from `sky/data/skystorage.py` so that it outputs to a local log file.

Thanks @landscapepainter! I will test it later.

Should we close this PR then?

**Comment by landscapepainter** [comment]
Closing as this PR is broken. Re-opened #2336

**Pull request closed without merging**
