### PR TITLE
[UX] Improve Formatting of Post Job Creation Logs

### PR DESCRIPTION
**Pull request by andylizf**
Enhance the formatting of logs shown after job creation for better readability and consistency with serve module's style, where:

https://github.com/skypilot-org/skypilot/blob/c0c17483d1f692ad639144050f5f6fa0966e47a5/sky/serve/core.py#L275-L304

### CODE REVIEW

**Comment by andylizf** [comment]
@cblmemo PTAL, thanks!

**Review by cblmemo — APPROVED** [review]
LGTM! cc @Michaelvll for a quick look before merging.

**Comment by Michaelvll** [comment]
This causes `test_minimal` to fail. Can we update the smoke test?

**Comment by andylizf** [comment]
Got it! I'll fix it soon.

**Pull request merged**
