### PR TITLE
[minor] Allow sky check to set enabled_clouds to empty

### PR DESCRIPTION
**Pull request by Michaelvll**
Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by concretevitamin** [comment]
Hey @Michaelvll could you remind me why this fix is necessary?

**Comment by Michaelvll** [comment]
> Hey @Michaelvll could you remind me why this fix is necessary?

This is to keep the behavior align for the output of `sky check` and the `enabled_clouds` in database. In the master, after removing all the cloud credentials and `sky check`, although it says all clouds are disabled, the `enabled_clouds` remains unchanged in the database.

It can cause some minor misalignment of the behavior for `sky launch`. When there was no cloud enabled before, `sky launch` will fail quickly. If a user removes all their clouds that were enabled and do a `sky check`, it will show that all the clouds are disabled, but if they `sky launch`, it will still show the optimizer table instead of failing quickly.

To reproduce on master:
1. `sky check` having aws enabled
2. `mv ~/.aws ~/.aws.bk` to disable the aws credential
3. `sky check` showing AWS being disabled already
4. `sky launch` will show the optimizer table, instead of just saying there is no cloud enabled.

**Comment by cblmemo** [comment]
> Hey @Michaelvll could you remind me why this fix is necessary?

If the user has one enabled cloud previously and the access token expired, then we should set enabled_clouds to empty instead of keeping this stale record?

**Review by concretevitamin — APPROVED** [review]

**Comment by concretevitamin** [comment]
Makes sense! LGTM

**Pull request merged**
