### PR TITLE
[Core] `source ~/.bashrc` when tailing managed jobs logs

### LINKED ISSUE #3531: [Jobs][k8s] Streaming logs fails for job controller
On https://github.com/skypilot-org/skypilot/commit/7f30ce5e732aa7beaf7e434d24f5d6818833283d (#3484), the job controller is not working on Kubernetes. 

When trying `sky jobs launch --cloud kubernetes --cpus 1 -- echo hi`, provisioning and setup works fine, but fails when it starts streaming logs:

```
I 05-09 16:45:25 cloud_vm_ray_backend.py:3300] Job submitted with Job ID: 1
D 05-09 16:45:25 command_runner.py:119] --- Proxy: ssh -tt -i ~/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -W %h:%p sky@127.0.0.1 -o ProxyCommand='/Users/romilb/.sky/port-forward-proxy-cmd.sh'  ---
Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.
Warning: Permanently added '10.112.0.12' (ED25519) to the list of known hosts.
kubectl port-forward failed. Error: E0509 23:47:09.406211    2570 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0509 23:47:09.406858    2570 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0509 23:47:09.408114    2570 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0509 23:47:09.408577    2570 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
I 05-09 23:47:09 utils.py:419] The job cluster is preempted or failed.
I 05-09 23:48:09 utils.py:446] Logs finished for job 1 (status: SUCCEEDED).
```

Logs:
* `sky jobs launch` [CLI logs](https://gist.github.com/romilbhardwaj/dbfa2f526bfbf2971f7b6925946f1d71)
* `sky jobs logs --controller 1` [controller logs](https://gist.github.com/romilbhardwaj/83192d3adcd226cec38dffec4b7718bc)
* [provision.log for the job on the controller](https://gist.github.com/romilbhardwaj/929fb1d9c1ef5a3d03641fc523280db5)

Works fine on https://github.com/skypilot-org/skypilot/commit/344459bbd119c8fd42a165746eb2f9170749a2c3.

To reproduce, use GKE or `sky local up` cluster. Run `sky jobs launch --cloud kubernetes --cpus 1 -- echo hi`. You may need to use the following `config.yaml` to force the controller on k8s:
```
jobs:
  controller:
    resources:
      cloud: kubernetes
      cpus: 4+
      memory: 4+
```

### PR DESCRIPTION
**Pull request by cblmemo**
Fixes #3531

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [x] Any manual or new tests for this PR (please specify below)
     - [x] The reproducable scripts in #3531, using GKE
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `conda deactivate; bash -i tests/backward_compatibility_tests.sh`

### CODE REVIEW

**Review by Michaelvll — APPROVED** [review]
Good catch @cblmemo ! Thanks for the fix.

**Comment by Michaelvll** [comment]
Do we need to source bashrc for the service as well?

**Comment by cblmemo** [comment]
> Do we need to source bashrc for the service as well? Also, should only source bashrc when the cluster is on k8s?

Good point! Lemme test and fix it if it is problematic.

**Comment by cblmemo** [comment]
> Do we need to source bashrc for the service as well? Also, should only source bashrc when the cluster is on k8s?

Fixed in #3537

**Pull request merged**
