### PR TITLE
[Provisioner] Fix open ports on Azure

### PR DESCRIPTION
**Pull request by cblmemo**
Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by Michaelvll** [comment]
Any update on this PR @cblmemo? It seems the smoke tests fail on the azure port related tests pretty often. : )

**Comment by cblmemo** [comment]
> Any update on this PR @cblmemo? It seems the smoke tests fail on the azure port related tests pretty often. : )

We could merge this PR first and it should make it better. There are some other problems in Azure API call and I'll take a look soon 🤔

**Comment by cblmemo** [comment]
> Any update on this PR @cblmemo? It seems the smoke tests fail on the azure port related tests pretty often. : )

Seems like the API calling bug no longer exists. This PR should fix the problem. 🫡 (I just run the smoke test and it passed)

**Review by Michaelvll — APPROVED** [review]
Thanks for fixing this @cblmemo! LGTM. Just tried to merge this PR to #2801 and it makes the smoke test for serving on Azure work.

**Pull request merged**
