### PR TITLE
Add ovhcloud

### PR DESCRIPTION
**Pull request by Wats0ns**
This PR adds OVHCloud as a provider for skypilot. This is a Beta version, no storage or zoning is handled yet

Tested (run the relevant ones):

- [x] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `bash tests/backward_comaptibility_tests.sh`

### CODE REVIEW

**Comment by Michaelvll** [comment]
Thanks for submitting the PR @Wats0ns! The support for OVHcloud is very exciting! Should we do a review pass for this PR? It would be nice if we can rebase the changes to the master branch instead of our 0.4.0 release. ; )

**Comment by Wats0ns** [comment]
Hey @Michaelvll, thanks for your time ! It seems that there is a test failing because it needs https://github.com/skypilot-org/skypilot-catalog/pull/48 to be approved, could you give it a go please ?
Thanks !

**Comment by Michaelvll** [comment]
> Hey @Michaelvll, thanks for your time ! It seems that there is a test failing because it needs [skypilot-org/skypilot-catalog#48](https://github.com/skypilot-org/skypilot-catalog/pull/48) to be approved, could you give it a go please ? Thanks !

Thanks for the fix @Wats0ns! I just merged the catalog PR. I will start reviewing the PR soon.

**Comment by concretevitamin** [comment]
Some user interest (#2974) in getting this merged.

**Comment by Michaelvll** [comment]
Hi @Wats0ns, sorry for the delay! We are migrating all our new cloud support to a new provisioner API. Could you help migrating the OVHcloud implementation to the new provisioner? This will significantly reduce the chance that we meet some unexpected bug during the debugging. : )

Please feel free to check out the doc here: https://docs.google.com/document/d/1oWox3qb3Kz3wXXSGg9ZJWwijoa99a3PIQUHBR8UgEGs/edit.

Also, if you would like to refer to it, here is an example with runpod: https://github.com/skypilot-org/skypilot/pull/2829

**Comment by kishb87** [comment]
Is there still a plan to add OVH or is this put on hold?

**Comment by Michaelvll** [comment]
> Is there still a plan to add OVH or is this put on hold?

Thanks for asking @kishb87! We are still very excited to support OVHCloud. The implementation of OVHCloud has to be migrated to our new provisioner API before we can start testing and merging the implementation: https://docs.google.com/document/d/1oWox3qb3Kz3wXXSGg9ZJWwijoa99a3PIQUHBR8UgEGs/edit#heading=h.nby65cfuzxoq

Any community contribution for the cloud is highly appreciated. : )

**Comment by Wats0ns** [comment]
Hello, @kishb87, I work at OVHCloud and developped the skypilot implementation. Due to a refactoring on skypilot side, I would need to do a migration for it to work with this new system and I don't have the time ATM. Could you please explain what you would do with it so that I can discuss it internally please ?
Thanks !

**Comment by kishb87** [comment]
Hi @ Wats0ns, we have an OVH account so I was curious. It would be another place where we could run workloads. I thought about taking your code and figuring out how to do the migration as a way to learn and get more familiar with the project, but right now I don't have the capacity.

**Pull request closed without merging**
